# Generated by Django 5.1.4 on 2025-01-03 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_range', models.CharField(max_length=100, verbose_name='Price Range')),
                ('start_time', models.DateTimeField(verbose_name='Auction Start Time')),
                ('end_time', models.DateTimeField(verbose_name='Auction End Time')),
                ('picture', models.ImageField(upload_to='paintings/', verbose_name='Painting Picture')),
                ('details', models.TextField(verbose_name='Additional Details')),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='myApp.painting')),
            ],
        ),
    ]
