# Generated by Django 5.1.4 on 2025-01-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_painting_sold_painting_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='status',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Sold', 'Sold')], default='Passed', max_length=20),
        ),
    ]
