# Generated by Django 5.1.4 on 2025-01-13 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_painting_user_alter_painting_winner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='user',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='owned_paintings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
