# Generated by Django 5.1.4 on 2025-01-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='privacy',
        ),
    ]
