# Generated by Django 5.1.4 on 2025-01-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_remove_transaction_admin_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='admin_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
