# Generated by Django 5.1.4 on 2025-02-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_rename_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
