# Generated by Django 5.1.4 on 2025-02-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_painting_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='approval_status',
        ),
    ]
