# Generated by Django 5.1.4 on 2025-02-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
