# Generated by Django 5.1.4 on 2025-03-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='payment_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
